[features]
seeds = false

[test]
startup_wait = 30000
[test.validator]
url = "https://api.devnet.solana.com"
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
[[test.validator.clone]]
address = "hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
